# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-08-07 03:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_auto_20170805_0123'),
        ('music', '0003_song_is_favorite'),
    ]

    operations = [
    ]
