# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-08-10 11:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0007_auto_20170810_1826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='artist',
            field=models.CharField(max_length=255, verbose_name=b'Artist'),
        ),
    ]
