# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-08-11 09:19
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0011_auto_20170810_2046'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='u_id',
            field=models.CharField(default=datetime.datetime(2017, 8, 11, 9, 19, 49, 166000, tzinfo=utc), max_length=32),
            preserve_default=False,
        ),
    ]
